site_name: 'Apicurio Documentation'

nav:
  - Overview: index.md
  - Quality Engineering Systems: qe.md
  - Google Drive Resources: gdrive.md
  - Productization:
    - Introduction: Productization/Introduction.md
    - Brew: Productization/brew.md
    - Errata: Productization/errata.md
    - Dist-Git: Productization/distgit.md
    - PNC: Productization/pnc.md
    - Comet: Productization/comet.md
    - OSBS: Productization/osbs.md
    - UMB: Productization/umb.md
    - code.engineering: Productization/gerrit.md


plugins:
  - techdocs-core