# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dist-git
  description: DistGit (Distribution Git) is Git with additional data storage. It is designed to hold container and package (rpm) code, and consists of these three main components- Git repositories, Lookaside cache to store source tarballs, Scripts to manage both.
  links:
    - url: http://pkgs.devel.redhat.com/cgit/
      title: Page
      icon: web
    - url: http://pkgs.devel.redhat.com/cgit/containers/integration-service-registry-kafkasql/
      title: Kafkasql Image
      icon: web
    - url: http://pkgs.devel.redhat.com/cgit/containers/integration-service-registry-sql/
      title: SQL Image
      icon: web
    - url: http://pkgs.devel.redhat.com/cgit/containers/integration-service-registry-operator/
      title: Operator Image
      icon: web
    - url: http://pkgs.devel.redhat.com/cgit/containers/integration-service-registry-operator-prod-operator-metadata/
      title: Operator-Metadata Image
      icon: web


  # annotations:
  #   backstage.io/source-location: url:https://github.com/Apicurio/apicurito
spec:
  type: project
  lifecycle: production
  owner: eng
  subcomponentOf : productization
  # system: upstream