# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: code.engineering
  description:  It is an internal mirror for the product source code. Internal systems(PNC/Brew) cannot use an external git repository, and therefore we need internal git repositories that will mirror the external one, so that the source code is in a more controlled and closed environment.


  links:
    - url: https://code.engineering.redhat.com/gerrit/
      title: Page
      icon: dashboard
    - url: https://code.engineering.redhat.com/gerrit/Documentation/index.html
      title: Gerrit documentation
      icon: web
    - url: https://docs.engineering.redhat.com/display/HTD/Gerrit+User+Guide
      title: Gerrit User Guide
      icon: web
    - url: https://code.engineering.redhat.com/gerrit/Documentation/access-control.html
      title: Gerrit Access Control
      icon: web
  # annotations:
  #   backstage.io/source-location: url:https://github.com/Apicurio/apicurito
spec:
  type: project
  lifecycle: production
  owner: eng
  subcomponentOf : productization
  # system: upstream