# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: productization
  description: Productization involves a series of processes and transformations which is applied to a community project, in order to be suitable as a commercial product. To perform productization related activities, we need productization systems.
  links:
    - url: https://github.com/Apicurio/apicurio-registry
      title: Upstream Repository
      icon: web
    - url: https://github.com/redhat-integration/apicurio-registry
      title: Midstream Repository
      icon: web
    - url: https://code.engineering.redhat.com/gerrit/admin/repos/Apicurio/apicurio-registry
      title: Downstream Repository
      icon: web
  annotations:
   backstage.io/source-location: url:https://github.com/Apicurio/apicurito
spec:
  type: project
  lifecycle: production
  owner: eng
  system: upstream