# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: UMB
  description: The Unified Message Bus is a messaging platform that integrates different systems used within Red Hat. It can be used to trigger jobs and actions based on messages published on topics available on the UMB. Almost all of the systems used for development and productization provide integration with UMB- Jira, Errata, Dist Git, PNC, brew, etc. 
  links:
    - url: https://docs.engineering.redhat.com/display/JP/Getting+Started+with+UMB+Integration
      title: Page
      icon: web 
    - url: https://mojo.redhat.com/docs/DOC-1072237
      title: UMB Documentation Index
      icon: web 
    - url: https://mojo.redhat.com/docs/DOC-1125330
      title: List of Topics
      icon: web 
    - url: https://docs.engineering.redhat.com/display/JP/Getting+Started+with+UMB+Integration
      title: Guide to Integrate Jenkins jobs with UMB
      icon: web
   # annotations:
  #   backstage.io/source-location: url:https://github.com/Apicurio/apicurito
spec:
  type: project
  lifecycle: production
  owner: eng
  subcomponentOf : productization
  # system: upstream