---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: upstream
  annotations:
    backstage.io/source-location: ""
spec:
  owner: eng