name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push image 
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3 
      - name: Login
        run: docker login -u="wtrocki" -p="${{secrets.QUAY_SECRET}}" quay.io
      - name: Prepare
        run: yarn && yarn tsc && yarn build                           
      - name: Build Image
        run: docker image build . -f packages/backend/Dockerfile -t quay.io/wtrocki/app-services-backstage 
      - name: Push To quay.io
        id: push-to-quay
        run: docker push quay.io/wtrocki/app-services-backstage
      
      
 
